package com.wms.dao.auto;

import com.wms.dao.example.AllocateStrategyTExample;
import com.wms.entity.auto.AllocateStrategyTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IAllocateStrategyTDao {
    long countByExample(AllocateStrategyTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALLOCATE_STRATEGY_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") AllocateStrategyTExample example);

    int deleteByExample(AllocateStrategyTExample example);

    int insert(AllocateStrategyTEntity record);

    int insertSelective(AllocateStrategyTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALLOCATE_STRATEGY_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    AllocateStrategyTEntity selectOneByExample(AllocateStrategyTExample example);

    List<AllocateStrategyTEntity> selectByExample(AllocateStrategyTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALLOCATE_STRATEGY_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") AllocateStrategyTEntity record, @Param("example") AllocateStrategyTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALLOCATE_STRATEGY_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") AllocateStrategyTEntity record, @Param("example") AllocateStrategyTExample example);

    int updateByExampleSelective(@Param("record") AllocateStrategyTEntity record, @Param("example") AllocateStrategyTExample example);

    int updateByExample(@Param("record") AllocateStrategyTEntity record, @Param("example") AllocateStrategyTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALLOCATE_STRATEGY_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") AllocateStrategyTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALLOCATE_STRATEGY_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") AllocateStrategyTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALLOCATE_STRATEGY_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Long allocateStrategyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALLOCATE_STRATEGY_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByPrimaryKey(@Param("version") Long version, @Param("key") Long allocateStrategyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALLOCATE_STRATEGY_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    AllocateStrategyTEntity selectByPrimaryKeyWithLogicalDelete(@Param("allocateStrategyId") Long allocateStrategyId, @Param("andLogicalDeleted") boolean andLogicalDeleted);
}