package com.wms.dao.auto;

import com.wms.dao.example.AreaDetailTExample;
import com.wms.entity.auto.AreaDetailTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IAreaDetailTDao {
    long countByExample(AreaDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AREA_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") AreaDetailTExample example);

    int deleteByExample(AreaDetailTExample example);

    int insert(AreaDetailTEntity record);

    int insertSelective(AreaDetailTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AREA_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    AreaDetailTEntity selectOneByExample(AreaDetailTExample example);

    List<AreaDetailTEntity> selectByExample(AreaDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AREA_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") AreaDetailTEntity record, @Param("example") AreaDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AREA_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") AreaDetailTEntity record, @Param("example") AreaDetailTExample example);

    int updateByExampleSelective(@Param("record") AreaDetailTEntity record, @Param("example") AreaDetailTExample example);

    int updateByExample(@Param("record") AreaDetailTEntity record, @Param("example") AreaDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AREA_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") AreaDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AREA_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") AreaDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AREA_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Long areaDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AREA_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByPrimaryKey(@Param("version") Long version, @Param("key") Long areaDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AREA_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    AreaDetailTEntity selectByPrimaryKeyWithLogicalDelete(@Param("areaDetailId") Long areaDetailId, @Param("andLogicalDeleted") boolean andLogicalDeleted);
}