package com.wms.dao.auto;

import com.wms.dao.example.EntSupplierTExample;
import com.wms.entity.auto.EntSupplierTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IEntSupplierTDao {
    long countByExample(EntSupplierTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENT_SUPPLIER_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") EntSupplierTExample example);

    int deleteByExample(EntSupplierTExample example);

    int insert(EntSupplierTEntity record);

    int insertSelective(EntSupplierTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENT_SUPPLIER_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    EntSupplierTEntity selectOneByExample(EntSupplierTExample example);

    List<EntSupplierTEntity> selectByExample(EntSupplierTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENT_SUPPLIER_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") EntSupplierTEntity record, @Param("example") EntSupplierTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENT_SUPPLIER_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") EntSupplierTEntity record, @Param("example") EntSupplierTExample example);

    int updateByExampleSelective(@Param("record") EntSupplierTEntity record, @Param("example") EntSupplierTExample example);

    int updateByExample(@Param("record") EntSupplierTEntity record, @Param("example") EntSupplierTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENT_SUPPLIER_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") EntSupplierTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENT_SUPPLIER_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") EntSupplierTExample example);
}