package com.wms.dao.auto;

import com.wms.dao.example.EntCarrierTExample;
import com.wms.entity.auto.EntCarrierTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IEntCarrierTDao {
    long countByExample(EntCarrierTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENT_CARRIER_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") EntCarrierTExample example);

    int deleteByExample(EntCarrierTExample example);

    int insert(EntCarrierTEntity record);

    int insertSelective(EntCarrierTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENT_CARRIER_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    EntCarrierTEntity selectOneByExample(EntCarrierTExample example);

    List<EntCarrierTEntity> selectByExample(EntCarrierTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENT_CARRIER_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") EntCarrierTEntity record, @Param("example") EntCarrierTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENT_CARRIER_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") EntCarrierTEntity record, @Param("example") EntCarrierTExample example);

    int updateByExampleSelective(@Param("record") EntCarrierTEntity record, @Param("example") EntCarrierTExample example);

    int updateByExample(@Param("record") EntCarrierTEntity record, @Param("example") EntCarrierTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENT_CARRIER_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") EntCarrierTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENT_CARRIER_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") EntCarrierTExample example);
}