package com.wms.dao.auto;

import com.wms.dao.example.EntCustomerTExample;
import com.wms.entity.auto.EntCustomerTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IEntCustomerTDao {
    long countByExample(EntCustomerTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENT_CUSTOMER_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") EntCustomerTExample example);

    int deleteByExample(EntCustomerTExample example);

    int insert(EntCustomerTEntity record);

    int insertSelective(EntCustomerTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENT_CUSTOMER_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    EntCustomerTEntity selectOneByExample(EntCustomerTExample example);

    List<EntCustomerTEntity> selectByExample(EntCustomerTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENT_CUSTOMER_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") EntCustomerTEntity record, @Param("example") EntCustomerTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENT_CUSTOMER_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") EntCustomerTEntity record, @Param("example") EntCustomerTExample example);

    int updateByExampleSelective(@Param("record") EntCustomerTEntity record, @Param("example") EntCustomerTExample example);

    int updateByExample(@Param("record") EntCustomerTEntity record, @Param("example") EntCustomerTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENT_CUSTOMER_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") EntCustomerTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENT_CUSTOMER_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") EntCustomerTExample example);
}