package com.wms.dao.auto;

import com.wms.dao.example.EntInventoryOnhandTExample;
import com.wms.entity.auto.EntInventoryOnhandTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IEntInventoryOnhandTDao {
    long countByExample(EntInventoryOnhandTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENT_INVETNROY_ONHAND_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") EntInventoryOnhandTExample example);

    int deleteByExample(EntInventoryOnhandTExample example);

    int insert(EntInventoryOnhandTEntity record);

    int insertSelective(EntInventoryOnhandTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENT_INVETNROY_ONHAND_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    EntInventoryOnhandTEntity selectOneByExample(EntInventoryOnhandTExample example);

    List<EntInventoryOnhandTEntity> selectByExample(EntInventoryOnhandTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENT_INVETNROY_ONHAND_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") EntInventoryOnhandTEntity record, @Param("example") EntInventoryOnhandTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENT_INVETNROY_ONHAND_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") EntInventoryOnhandTEntity record, @Param("example") EntInventoryOnhandTExample example);

    int updateByExampleSelective(@Param("record") EntInventoryOnhandTEntity record, @Param("example") EntInventoryOnhandTExample example);

    int updateByExample(@Param("record") EntInventoryOnhandTEntity record, @Param("example") EntInventoryOnhandTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENT_INVETNROY_ONHAND_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") EntInventoryOnhandTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENT_INVETNROY_ONHAND_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") EntInventoryOnhandTExample example);
}