package com.wms.dao.auto;

import com.wms.dao.example.InboundDetailTExample;
import com.wms.entity.auto.InboundDetailTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IInboundDetailTDao {
    long countByExample(InboundDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INBOUND_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") InboundDetailTExample example);

    int deleteByExample(InboundDetailTExample example);

    int insert(InboundDetailTEntity record);

    int insertSelective(InboundDetailTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INBOUND_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    InboundDetailTEntity selectOneByExample(InboundDetailTExample example);

    List<InboundDetailTEntity> selectByExample(InboundDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INBOUND_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") InboundDetailTEntity record, @Param("example") InboundDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INBOUND_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") InboundDetailTEntity record, @Param("example") InboundDetailTExample example);

    int updateByExampleSelective(@Param("record") InboundDetailTEntity record, @Param("example") InboundDetailTExample example);

    int updateByExample(@Param("record") InboundDetailTEntity record, @Param("example") InboundDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INBOUND_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") InboundDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INBOUND_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") InboundDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INBOUND_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Long inboundDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INBOUND_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByPrimaryKey(@Param("version") Long version, @Param("key") Long inboundDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INBOUND_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    InboundDetailTEntity selectByPrimaryKeyWithLogicalDelete(@Param("inboundDetailId") Long inboundDetailId, @Param("andLogicalDeleted") boolean andLogicalDeleted);
}