package com.wms.dao.auto;

import com.wms.dao.example.InboundCancelDetailTExample;
import com.wms.entity.auto.InboundCancelDetailTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IInboundCancelDetailTDao {
    long countByExample(InboundCancelDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INBOUND_CANCEL_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") InboundCancelDetailTExample example);

    int deleteByExample(InboundCancelDetailTExample example);

    int insert(InboundCancelDetailTEntity record);

    int insertSelective(InboundCancelDetailTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INBOUND_CANCEL_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    InboundCancelDetailTEntity selectOneByExample(InboundCancelDetailTExample example);

    List<InboundCancelDetailTEntity> selectByExample(InboundCancelDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INBOUND_CANCEL_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") InboundCancelDetailTEntity record, @Param("example") InboundCancelDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INBOUND_CANCEL_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") InboundCancelDetailTEntity record, @Param("example") InboundCancelDetailTExample example);

    int updateByExampleSelective(@Param("record") InboundCancelDetailTEntity record, @Param("example") InboundCancelDetailTExample example);

    int updateByExample(@Param("record") InboundCancelDetailTEntity record, @Param("example") InboundCancelDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INBOUND_CANCEL_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") InboundCancelDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INBOUND_CANCEL_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") InboundCancelDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INBOUND_CANCEL_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Long inboundCancelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INBOUND_CANCEL_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByPrimaryKey(@Param("version") Long version, @Param("key") Long inboundCancelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INBOUND_CANCEL_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    InboundCancelDetailTEntity selectByPrimaryKeyWithLogicalDelete(@Param("inboundCancelId") Long inboundCancelId, @Param("andLogicalDeleted") boolean andLogicalDeleted);
}