package com.wms.dao.auto;

import com.wms.dao.example.InboundCancelHeaderTExample;
import com.wms.entity.auto.InboundCancelHeaderTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IInboundCancelHeaderTDao {
    long countByExample(InboundCancelHeaderTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INBOUND_CANCEL_HEADER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") InboundCancelHeaderTExample example);

    int deleteByExample(InboundCancelHeaderTExample example);

    int insert(InboundCancelHeaderTEntity record);

    int insertSelective(InboundCancelHeaderTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INBOUND_CANCEL_HEADER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    InboundCancelHeaderTEntity selectOneByExample(InboundCancelHeaderTExample example);

    List<InboundCancelHeaderTEntity> selectByExample(InboundCancelHeaderTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INBOUND_CANCEL_HEADER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") InboundCancelHeaderTEntity record, @Param("example") InboundCancelHeaderTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INBOUND_CANCEL_HEADER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") InboundCancelHeaderTEntity record, @Param("example") InboundCancelHeaderTExample example);

    int updateByExampleSelective(@Param("record") InboundCancelHeaderTEntity record, @Param("example") InboundCancelHeaderTExample example);

    int updateByExample(@Param("record") InboundCancelHeaderTEntity record, @Param("example") InboundCancelHeaderTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INBOUND_CANCEL_HEADER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") InboundCancelHeaderTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INBOUND_CANCEL_HEADER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") InboundCancelHeaderTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INBOUND_CANCEL_HEADER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Long inboundCancelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INBOUND_CANCEL_HEADER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByPrimaryKey(@Param("version") Long version, @Param("key") Long inboundCancelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INBOUND_CANCEL_HEADER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    InboundCancelHeaderTEntity selectByPrimaryKeyWithLogicalDelete(@Param("inboundCancelId") Long inboundCancelId, @Param("andLogicalDeleted") boolean andLogicalDeleted);
}