package com.wms.dao.auto;

import com.wms.dao.example.InventoryAdjustmentDetailTExample;
import com.wms.entity.auto.InventoryAdjustmentDetailTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IInventoryAdjustmentDetailTDao {
    long countByExample(InventoryAdjustmentDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_ADJUSTMENT_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") InventoryAdjustmentDetailTExample example);

    int deleteByExample(InventoryAdjustmentDetailTExample example);

    int insert(InventoryAdjustmentDetailTEntity record);

    int insertSelective(InventoryAdjustmentDetailTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_ADJUSTMENT_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    InventoryAdjustmentDetailTEntity selectOneByExample(InventoryAdjustmentDetailTExample example);

    List<InventoryAdjustmentDetailTEntity> selectByExample(InventoryAdjustmentDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_ADJUSTMENT_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") InventoryAdjustmentDetailTEntity record, @Param("example") InventoryAdjustmentDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_ADJUSTMENT_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") InventoryAdjustmentDetailTEntity record, @Param("example") InventoryAdjustmentDetailTExample example);

    int updateByExampleSelective(@Param("record") InventoryAdjustmentDetailTEntity record, @Param("example") InventoryAdjustmentDetailTExample example);

    int updateByExample(@Param("record") InventoryAdjustmentDetailTEntity record, @Param("example") InventoryAdjustmentDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_ADJUSTMENT_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") InventoryAdjustmentDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_ADJUSTMENT_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") InventoryAdjustmentDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_ADJUSTMENT_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Long inventoryAdjustmentDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_ADJUSTMENT_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByPrimaryKey(@Param("version") Long version, @Param("key") Long inventoryAdjustmentDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_ADJUSTMENT_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    InventoryAdjustmentDetailTEntity selectByPrimaryKeyWithLogicalDelete(@Param("inventoryAdjustmentDetailId") Long inventoryAdjustmentDetailId, @Param("andLogicalDeleted") boolean andLogicalDeleted);
}