package com.wms.dao.auto;

import com.wms.dao.example.InventoryAdjustmentHeaderTExample;
import com.wms.entity.auto.InventoryAdjustmentHeaderTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IInventoryAdjustmentHeaderTDao {
    long countByExample(InventoryAdjustmentHeaderTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_ADJUSTMENT_HEADER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") InventoryAdjustmentHeaderTExample example);

    int deleteByExample(InventoryAdjustmentHeaderTExample example);

    int insert(InventoryAdjustmentHeaderTEntity record);

    int insertSelective(InventoryAdjustmentHeaderTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_ADJUSTMENT_HEADER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    InventoryAdjustmentHeaderTEntity selectOneByExample(InventoryAdjustmentHeaderTExample example);

    List<InventoryAdjustmentHeaderTEntity> selectByExample(InventoryAdjustmentHeaderTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_ADJUSTMENT_HEADER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") InventoryAdjustmentHeaderTEntity record, @Param("example") InventoryAdjustmentHeaderTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_ADJUSTMENT_HEADER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") InventoryAdjustmentHeaderTEntity record, @Param("example") InventoryAdjustmentHeaderTExample example);

    int updateByExampleSelective(@Param("record") InventoryAdjustmentHeaderTEntity record, @Param("example") InventoryAdjustmentHeaderTExample example);

    int updateByExample(@Param("record") InventoryAdjustmentHeaderTEntity record, @Param("example") InventoryAdjustmentHeaderTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_ADJUSTMENT_HEADER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") InventoryAdjustmentHeaderTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_ADJUSTMENT_HEADER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") InventoryAdjustmentHeaderTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_ADJUSTMENT_HEADER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Long inventoryAdjustmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_ADJUSTMENT_HEADER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByPrimaryKey(@Param("version") Long version, @Param("key") Long inventoryAdjustmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_ADJUSTMENT_HEADER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    InventoryAdjustmentHeaderTEntity selectByPrimaryKeyWithLogicalDelete(@Param("inventoryAdjustmentId") Long inventoryAdjustmentId, @Param("andLogicalDeleted") boolean andLogicalDeleted);
}