package com.wms.dao.auto;

import com.wms.dao.example.InventoryLockedTExample;
import com.wms.entity.auto.InventoryLockedTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IInventoryLockedTDao {
    long countByExample(InventoryLockedTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_LOCKED_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") InventoryLockedTExample example);

    int deleteByExample(InventoryLockedTExample example);

    int insert(InventoryLockedTEntity record);

    int insertSelective(InventoryLockedTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_LOCKED_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    InventoryLockedTEntity selectOneByExample(InventoryLockedTExample example);

    List<InventoryLockedTEntity> selectByExample(InventoryLockedTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_LOCKED_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") InventoryLockedTEntity record, @Param("example") InventoryLockedTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_LOCKED_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") InventoryLockedTEntity record, @Param("example") InventoryLockedTExample example);

    int updateByExampleSelective(@Param("record") InventoryLockedTEntity record, @Param("example") InventoryLockedTExample example);

    int updateByExample(@Param("record") InventoryLockedTEntity record, @Param("example") InventoryLockedTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_LOCKED_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") InventoryLockedTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_LOCKED_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") InventoryLockedTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_LOCKED_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Long inventoryLockedId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_LOCKED_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByPrimaryKey(@Param("version") Long version, @Param("key") Long inventoryLockedId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_LOCKED_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    InventoryLockedTEntity selectByPrimaryKeyWithLogicalDelete(@Param("inventoryLockedId") Long inventoryLockedId, @Param("andLogicalDeleted") boolean andLogicalDeleted);
}