package com.wms.dao.auto;

import com.wms.dao.example.InventoryTransactionTExample;
import com.wms.entity.auto.InventoryTransactionTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IInventoryTransactionTDao {
    long countByExample(InventoryTransactionTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_TRANSACTION_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") InventoryTransactionTExample example);

    int deleteByExample(InventoryTransactionTExample example);

    int insert(InventoryTransactionTEntity record);

    int insertSelective(InventoryTransactionTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_TRANSACTION_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    InventoryTransactionTEntity selectOneByExample(InventoryTransactionTExample example);

    List<InventoryTransactionTEntity> selectByExample(InventoryTransactionTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_TRANSACTION_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") InventoryTransactionTEntity record, @Param("example") InventoryTransactionTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_TRANSACTION_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") InventoryTransactionTEntity record, @Param("example") InventoryTransactionTExample example);

    int updateByExampleSelective(@Param("record") InventoryTransactionTEntity record, @Param("example") InventoryTransactionTExample example);

    int updateByExample(@Param("record") InventoryTransactionTEntity record, @Param("example") InventoryTransactionTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_TRANSACTION_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") InventoryTransactionTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_TRANSACTION_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") InventoryTransactionTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_TRANSACTION_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Long transactionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_TRANSACTION_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByPrimaryKey(@Param("version") Long version, @Param("key") Long transactionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVENTORY_TRANSACTION_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    InventoryTransactionTEntity selectByPrimaryKeyWithLogicalDelete(@Param("transactionId") Long transactionId, @Param("andLogicalDeleted") boolean andLogicalDeleted);
}