package com.wms.dao.auto;

import com.wms.dao.example.LocationTExample;
import com.wms.entity.auto.LocationTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ILocationTDao {
    long countByExample(LocationTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOCATION_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") LocationTExample example);

    int deleteByExample(LocationTExample example);

    int insert(LocationTEntity record);

    int insertSelective(LocationTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOCATION_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LocationTEntity selectOneByExample(LocationTExample example);

    List<LocationTEntity> selectByExample(LocationTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOCATION_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") LocationTEntity record, @Param("example") LocationTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOCATION_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") LocationTEntity record, @Param("example") LocationTExample example);

    int updateByExampleSelective(@Param("record") LocationTEntity record, @Param("example") LocationTExample example);

    int updateByExample(@Param("record") LocationTEntity record, @Param("example") LocationTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOCATION_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LocationTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOCATION_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") LocationTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOCATION_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Long locationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOCATION_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByPrimaryKey(@Param("version") Long version, @Param("key") Long locationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOCATION_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LocationTEntity selectByPrimaryKeyWithLogicalDelete(@Param("locationId") Long locationId, @Param("andLogicalDeleted") boolean andLogicalDeleted);
}