package com.wms.dao.auto;

import com.wms.dao.example.LpnTExample;
import com.wms.entity.auto.LpnTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ILpnTDao {
    long countByExample(LpnTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LPN_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") LpnTExample example);

    int deleteByExample(LpnTExample example);

    int insert(LpnTEntity record);

    int insertSelective(LpnTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LPN_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LpnTEntity selectOneByExample(LpnTExample example);

    List<LpnTEntity> selectByExample(LpnTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LPN_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") LpnTEntity record, @Param("example") LpnTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LPN_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") LpnTEntity record, @Param("example") LpnTExample example);

    int updateByExampleSelective(@Param("record") LpnTEntity record, @Param("example") LpnTExample example);

    int updateByExample(@Param("record") LpnTEntity record, @Param("example") LpnTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LPN_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LpnTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LPN_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") LpnTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LPN_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Long lpnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LPN_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByPrimaryKey(@Param("version") Long version, @Param("key") Long lpnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LPN_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LpnTEntity selectByPrimaryKeyWithLogicalDelete(@Param("lpnId") Long lpnId, @Param("andLogicalDeleted") boolean andLogicalDeleted);
}