package com.wms.dao.auto;

import com.wms.dao.example.OutboundDetailTExample;
import com.wms.entity.auto.OutboundDetailTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IOutboundDetailTDao {
    long countByExample(OutboundDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTBOUND_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") OutboundDetailTExample example);

    int deleteByExample(OutboundDetailTExample example);

    int insert(OutboundDetailTEntity record);

    int insertSelective(OutboundDetailTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTBOUND_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    OutboundDetailTEntity selectOneByExample(OutboundDetailTExample example);

    List<OutboundDetailTEntity> selectByExample(OutboundDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTBOUND_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") OutboundDetailTEntity record, @Param("example") OutboundDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTBOUND_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") OutboundDetailTEntity record, @Param("example") OutboundDetailTExample example);

    int updateByExampleSelective(@Param("record") OutboundDetailTEntity record, @Param("example") OutboundDetailTExample example);

    int updateByExample(@Param("record") OutboundDetailTEntity record, @Param("example") OutboundDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTBOUND_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") OutboundDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTBOUND_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") OutboundDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTBOUND_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Long outboundDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTBOUND_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByPrimaryKey(@Param("version") Long version, @Param("key") Long outboundDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTBOUND_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    OutboundDetailTEntity selectByPrimaryKeyWithLogicalDelete(@Param("outboundDetailId") Long outboundDetailId, @Param("andLogicalDeleted") boolean andLogicalDeleted);
}