package com.wms.dao.auto;

import com.wms.dao.example.OutboundHeaderTExample;
import com.wms.entity.auto.OutboundHeaderTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IOutboundHeaderTDao {
    long countByExample(OutboundHeaderTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTBOUND_HEADER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") OutboundHeaderTExample example);

    int deleteByExample(OutboundHeaderTExample example);

    int insert(OutboundHeaderTEntity record);

    int insertSelective(OutboundHeaderTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTBOUND_HEADER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    OutboundHeaderTEntity selectOneByExample(OutboundHeaderTExample example);

    List<OutboundHeaderTEntity> selectByExample(OutboundHeaderTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTBOUND_HEADER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") OutboundHeaderTEntity record, @Param("example") OutboundHeaderTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTBOUND_HEADER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") OutboundHeaderTEntity record, @Param("example") OutboundHeaderTExample example);

    int updateByExampleSelective(@Param("record") OutboundHeaderTEntity record, @Param("example") OutboundHeaderTExample example);

    int updateByExample(@Param("record") OutboundHeaderTEntity record, @Param("example") OutboundHeaderTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTBOUND_HEADER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") OutboundHeaderTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTBOUND_HEADER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") OutboundHeaderTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTBOUND_HEADER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Long outboundHeaderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTBOUND_HEADER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByPrimaryKey(@Param("version") Long version, @Param("key") Long outboundHeaderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTBOUND_HEADER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    OutboundHeaderTEntity selectByPrimaryKeyWithLogicalDelete(@Param("outboundHeaderId") Long outboundHeaderId, @Param("andLogicalDeleted") boolean andLogicalDeleted);
}