package com.wms.dao.auto;

import com.wms.dao.example.OwnerTExample;
import com.wms.entity.auto.OwnerTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IOwnerTDao {
    long countByExample(OwnerTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OWNER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") OwnerTExample example);

    int deleteByExample(OwnerTExample example);

    int insert(OwnerTEntity record);

    int insertSelective(OwnerTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OWNER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    OwnerTEntity selectOneByExample(OwnerTExample example);

    List<OwnerTEntity> selectByExample(OwnerTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OWNER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") OwnerTEntity record, @Param("example") OwnerTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OWNER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") OwnerTEntity record, @Param("example") OwnerTExample example);

    int updateByExampleSelective(@Param("record") OwnerTEntity record, @Param("example") OwnerTExample example);

    int updateByExample(@Param("record") OwnerTEntity record, @Param("example") OwnerTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OWNER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") OwnerTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OWNER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") OwnerTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OWNER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Long ownerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OWNER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByPrimaryKey(@Param("version") Long version, @Param("key") Long ownerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OWNER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    OwnerTEntity selectByPrimaryKeyWithLogicalDelete(@Param("ownerId") Long ownerId, @Param("andLogicalDeleted") boolean andLogicalDeleted);
}