package com.wms.dao.auto;

import com.wms.dao.example.PackTExample;
import com.wms.entity.auto.PackTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IPackTDao {
    long countByExample(PackTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PACK_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") PackTExample example);

    int deleteByExample(PackTExample example);

    int insert(PackTEntity record);

    int insertSelective(PackTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PACK_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PackTEntity selectOneByExample(PackTExample example);

    List<PackTEntity> selectByExample(PackTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PACK_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") PackTEntity record, @Param("example") PackTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PACK_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") PackTEntity record, @Param("example") PackTExample example);

    int updateByExampleSelective(@Param("record") PackTEntity record, @Param("example") PackTExample example);

    int updateByExample(@Param("record") PackTEntity record, @Param("example") PackTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PACK_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") PackTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PACK_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") PackTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PACK_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Long packId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PACK_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByPrimaryKey(@Param("version") Long version, @Param("key") Long packId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PACK_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PackTEntity selectByPrimaryKeyWithLogicalDelete(@Param("packId") Long packId, @Param("andLogicalDeleted") boolean andLogicalDeleted);
}