package com.wms.dao.auto;

import com.wms.dao.example.PutawayLocationLockTExample;
import com.wms.entity.auto.PutawayLocationLockTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IPutawayLocationLockTDao {
    long countByExample(PutawayLocationLockTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUTAWAY_LOCATION_LOCK_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") PutawayLocationLockTExample example);

    int deleteByExample(PutawayLocationLockTExample example);

    int insert(PutawayLocationLockTEntity record);

    int insertSelective(PutawayLocationLockTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUTAWAY_LOCATION_LOCK_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PutawayLocationLockTEntity selectOneByExample(PutawayLocationLockTExample example);

    List<PutawayLocationLockTEntity> selectByExample(PutawayLocationLockTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUTAWAY_LOCATION_LOCK_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") PutawayLocationLockTEntity record, @Param("example") PutawayLocationLockTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUTAWAY_LOCATION_LOCK_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") PutawayLocationLockTEntity record, @Param("example") PutawayLocationLockTExample example);

    int updateByExampleSelective(@Param("record") PutawayLocationLockTEntity record, @Param("example") PutawayLocationLockTExample example);

    int updateByExample(@Param("record") PutawayLocationLockTEntity record, @Param("example") PutawayLocationLockTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUTAWAY_LOCATION_LOCK_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") PutawayLocationLockTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUTAWAY_LOCATION_LOCK_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") PutawayLocationLockTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUTAWAY_LOCATION_LOCK_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Long putawayLocationLockId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUTAWAY_LOCATION_LOCK_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByPrimaryKey(@Param("version") Long version, @Param("key") Long putawayLocationLockId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUTAWAY_LOCATION_LOCK_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PutawayLocationLockTEntity selectByPrimaryKeyWithLogicalDelete(@Param("putawayLocationLockId") Long putawayLocationLockId, @Param("andLogicalDeleted") boolean andLogicalDeleted);
}