package com.wms.dao.auto;

import com.wms.dao.example.PutawayStrategyTExample;
import com.wms.entity.auto.PutawayStrategyTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IPutawayStrategyTDao {
    long countByExample(PutawayStrategyTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUTAWAY_STRATEGY_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") PutawayStrategyTExample example);

    int deleteByExample(PutawayStrategyTExample example);

    int insert(PutawayStrategyTEntity record);

    int insertSelective(PutawayStrategyTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUTAWAY_STRATEGY_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PutawayStrategyTEntity selectOneByExample(PutawayStrategyTExample example);

    List<PutawayStrategyTEntity> selectByExample(PutawayStrategyTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUTAWAY_STRATEGY_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") PutawayStrategyTEntity record, @Param("example") PutawayStrategyTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUTAWAY_STRATEGY_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") PutawayStrategyTEntity record, @Param("example") PutawayStrategyTExample example);

    int updateByExampleSelective(@Param("record") PutawayStrategyTEntity record, @Param("example") PutawayStrategyTExample example);

    int updateByExample(@Param("record") PutawayStrategyTEntity record, @Param("example") PutawayStrategyTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUTAWAY_STRATEGY_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") PutawayStrategyTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUTAWAY_STRATEGY_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") PutawayStrategyTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUTAWAY_STRATEGY_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Long putawayStrategyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUTAWAY_STRATEGY_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByPrimaryKey(@Param("version") Long version, @Param("key") Long putawayStrategyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUTAWAY_STRATEGY_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PutawayStrategyTEntity selectByPrimaryKeyWithLogicalDelete(@Param("putawayStrategyId") Long putawayStrategyId, @Param("andLogicalDeleted") boolean andLogicalDeleted);
}