package com.wms.dao.auto;

import com.wms.dao.example.SysConfigTExample;
import com.wms.entity.auto.SysConfigTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ISysConfigTDao {
    long countByExample(SysConfigTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") SysConfigTExample example);

    int deleteByExample(SysConfigTExample example);

    int insert(SysConfigTEntity record);

    int insertSelective(SysConfigTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SysConfigTEntity selectOneByExample(SysConfigTExample example);

    List<SysConfigTEntity> selectByExample(SysConfigTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") SysConfigTEntity record, @Param("example") SysConfigTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") SysConfigTEntity record, @Param("example") SysConfigTExample example);

    int updateByExampleSelective(@Param("record") SysConfigTEntity record, @Param("example") SysConfigTExample example);

    int updateByExample(@Param("record") SysConfigTEntity record, @Param("example") SysConfigTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") SysConfigTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") SysConfigTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Long configId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByPrimaryKey(@Param("version") Long version, @Param("key") Long configId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CONFIG_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SysConfigTEntity selectByPrimaryKeyWithLogicalDelete(@Param("configId") Long configId, @Param("andLogicalDeleted") boolean andLogicalDeleted);
}