package com.wms.dao.auto;

import com.wms.dao.example.SysPermissionTExample;
import com.wms.entity.auto.SysPermissionTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ISysPermissionTDao {
    long countByExample(SysPermissionTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PERMISSION_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") SysPermissionTExample example);

    int deleteByExample(SysPermissionTExample example);

    int insert(SysPermissionTEntity record);

    int insertSelective(SysPermissionTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PERMISSION_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SysPermissionTEntity selectOneByExample(SysPermissionTExample example);

    List<SysPermissionTEntity> selectByExample(SysPermissionTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PERMISSION_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") SysPermissionTEntity record, @Param("example") SysPermissionTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PERMISSION_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") SysPermissionTEntity record, @Param("example") SysPermissionTExample example);

    int updateByExampleSelective(@Param("record") SysPermissionTEntity record, @Param("example") SysPermissionTExample example);

    int updateByExample(@Param("record") SysPermissionTEntity record, @Param("example") SysPermissionTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PERMISSION_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") SysPermissionTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_PERMISSION_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") SysPermissionTExample example);
}