package com.wms.dao.auto;

import com.wms.dao.example.SysLocaleVExample;
import com.wms.entity.auto.SysLocaleVEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ISysLocaleVDao {
    long countByExample(SysLocaleVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_LOCALE_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") SysLocaleVExample example);

    int deleteByExample(SysLocaleVExample example);

    int insert(SysLocaleVEntity record);

    int insertSelective(SysLocaleVEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_LOCALE_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SysLocaleVEntity selectOneByExample(SysLocaleVExample example);

    List<SysLocaleVEntity> selectByExample(SysLocaleVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_LOCALE_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") SysLocaleVEntity record, @Param("example") SysLocaleVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_LOCALE_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") SysLocaleVEntity record, @Param("example") SysLocaleVExample example);

    int updateByExampleSelective(@Param("record") SysLocaleVEntity record, @Param("example") SysLocaleVExample example);

    int updateByExample(@Param("record") SysLocaleVEntity record, @Param("example") SysLocaleVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_LOCALE_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") SysLocaleVExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_LOCALE_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") SysLocaleVExample example);
}