package com.wms.dao.auto;

import com.wms.dao.example.SysCodelistTExample;
import com.wms.entity.auto.SysCodelistTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ISysCodelistTDao {
    long countByExample(SysCodelistTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CODELIST_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") SysCodelistTExample example);

    int deleteByExample(SysCodelistTExample example);

    int insert(SysCodelistTEntity record);

    int insertSelective(SysCodelistTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CODELIST_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SysCodelistTEntity selectOneByExample(SysCodelistTExample example);

    List<SysCodelistTEntity> selectByExample(SysCodelistTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CODELIST_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") SysCodelistTEntity record, @Param("example") SysCodelistTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CODELIST_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") SysCodelistTEntity record, @Param("example") SysCodelistTExample example);

    int updateByExampleSelective(@Param("record") SysCodelistTEntity record, @Param("example") SysCodelistTExample example);

    int updateByExample(@Param("record") SysCodelistTEntity record, @Param("example") SysCodelistTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CODELIST_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") SysCodelistTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CODELIST_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") SysCodelistTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CODELIST_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Long codelistId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CODELIST_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByPrimaryKey(@Param("version") Long version, @Param("key") Long codelistId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CODELIST_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SysCodelistTEntity selectByPrimaryKeyWithLogicalDelete(@Param("codelistId") Long codelistId, @Param("andLogicalDeleted") boolean andLogicalDeleted);
}