package com.wms.dao.auto;

import com.wms.dao.example.SysOrderNumberTExample;
import com.wms.entity.auto.SysOrderNumberTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ISysOrderNumberTDao {
    long countByExample(SysOrderNumberTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ORDER_NUMBER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") SysOrderNumberTExample example);

    int deleteByExample(SysOrderNumberTExample example);

    int insert(SysOrderNumberTEntity record);

    int insertSelective(SysOrderNumberTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ORDER_NUMBER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SysOrderNumberTEntity selectOneByExample(SysOrderNumberTExample example);

    List<SysOrderNumberTEntity> selectByExample(SysOrderNumberTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ORDER_NUMBER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") SysOrderNumberTEntity record, @Param("example") SysOrderNumberTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ORDER_NUMBER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") SysOrderNumberTEntity record, @Param("example") SysOrderNumberTExample example);

    int updateByExampleSelective(@Param("record") SysOrderNumberTEntity record, @Param("example") SysOrderNumberTExample example);

    int updateByExample(@Param("record") SysOrderNumberTEntity record, @Param("example") SysOrderNumberTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ORDER_NUMBER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") SysOrderNumberTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ORDER_NUMBER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") SysOrderNumberTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ORDER_NUMBER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Long orderNumberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ORDER_NUMBER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByPrimaryKey(@Param("version") Long version, @Param("key") Long orderNumberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ORDER_NUMBER_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SysOrderNumberTEntity selectByPrimaryKeyWithLogicalDelete(@Param("orderNumberId") Long orderNumberId, @Param("andLogicalDeleted") boolean andLogicalDeleted);
}