package com.wms.dao.auto;

import com.wms.dao.example.SysRoleDataTExample;
import com.wms.entity.auto.SysRoleDataTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ISysRoleDataTDao {
    long countByExample(SysRoleDataTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_DATA_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") SysRoleDataTExample example);

    int deleteByExample(SysRoleDataTExample example);

    int insert(SysRoleDataTEntity record);

    int insertSelective(SysRoleDataTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_DATA_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SysRoleDataTEntity selectOneByExample(SysRoleDataTExample example);

    List<SysRoleDataTEntity> selectByExample(SysRoleDataTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_DATA_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") SysRoleDataTEntity record, @Param("example") SysRoleDataTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_DATA_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") SysRoleDataTEntity record, @Param("example") SysRoleDataTExample example);

    int updateByExampleSelective(@Param("record") SysRoleDataTEntity record, @Param("example") SysRoleDataTExample example);

    int updateByExample(@Param("record") SysRoleDataTEntity record, @Param("example") SysRoleDataTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_DATA_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") SysRoleDataTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_DATA_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") SysRoleDataTExample example);
}