package com.wms.dao.auto;

import com.wms.dao.example.SysCodelkupTExample;
import com.wms.entity.auto.SysCodelkupTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ISysCodelkupTDao {
    long countByExample(SysCodelkupTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CODELKUP_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") SysCodelkupTExample example);

    int deleteByExample(SysCodelkupTExample example);

    int insert(SysCodelkupTEntity record);

    int insertSelective(SysCodelkupTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CODELKUP_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SysCodelkupTEntity selectOneByExample(SysCodelkupTExample example);

    List<SysCodelkupTEntity> selectByExample(SysCodelkupTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CODELKUP_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") SysCodelkupTEntity record, @Param("example") SysCodelkupTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CODELKUP_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") SysCodelkupTEntity record, @Param("example") SysCodelkupTExample example);

    int updateByExampleSelective(@Param("record") SysCodelkupTEntity record, @Param("example") SysCodelkupTExample example);

    int updateByExample(@Param("record") SysCodelkupTEntity record, @Param("example") SysCodelkupTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CODELKUP_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") SysCodelkupTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CODELKUP_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") SysCodelkupTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CODELKUP_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Long codelkupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CODELKUP_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByPrimaryKey(@Param("version") Long version, @Param("key") Long codelkupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_CODELKUP_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SysCodelkupTEntity selectByPrimaryKeyWithLogicalDelete(@Param("codelkupId") Long codelkupId, @Param("andLogicalDeleted") boolean andLogicalDeleted);
}