package com.wms.dao.auto;

import com.wms.dao.example.SysOperLogTExample;
import com.wms.entity.auto.SysOperLogTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ISysOperLogTDao {
    long countByExample(SysOperLogTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_OPER_LOG_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") SysOperLogTExample example);

    int deleteByExample(SysOperLogTExample example);

    int insert(SysOperLogTEntity record);

    int insertSelective(SysOperLogTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_OPER_LOG_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SysOperLogTEntity selectOneByExample(SysOperLogTExample example);

    List<SysOperLogTEntity> selectByExample(SysOperLogTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_OPER_LOG_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") SysOperLogTEntity record, @Param("example") SysOperLogTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_OPER_LOG_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") SysOperLogTEntity record, @Param("example") SysOperLogTExample example);

    int updateByExampleSelective(@Param("record") SysOperLogTEntity record, @Param("example") SysOperLogTExample example);

    int updateByExample(@Param("record") SysOperLogTEntity record, @Param("example") SysOperLogTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_OPER_LOG_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") SysOperLogTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_OPER_LOG_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") SysOperLogTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_OPER_LOG_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Long operLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_OPER_LOG_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByPrimaryKey(@Param("version") Long version, @Param("key") Long operLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_OPER_LOG_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SysOperLogTEntity selectByPrimaryKeyWithLogicalDelete(@Param("operLogId") Long operLogId, @Param("andLogicalDeleted") boolean andLogicalDeleted);
}