package com.wms.dao.auto;

import com.wms.dao.example.SysWarehousesTExample;
import com.wms.entity.auto.SysWarehousesTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ISysWarehousesTDao {
    long countByExample(SysWarehousesTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_WAREHOUSES_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") SysWarehousesTExample example);

    int deleteByExample(SysWarehousesTExample example);

    int insert(SysWarehousesTEntity record);

    int insertSelective(SysWarehousesTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_WAREHOUSES_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SysWarehousesTEntity selectOneByExample(SysWarehousesTExample example);

    List<SysWarehousesTEntity> selectByExample(SysWarehousesTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_WAREHOUSES_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") SysWarehousesTEntity record, @Param("example") SysWarehousesTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_WAREHOUSES_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") SysWarehousesTEntity record, @Param("example") SysWarehousesTExample example);

    int updateByExampleSelective(@Param("record") SysWarehousesTEntity record, @Param("example") SysWarehousesTExample example);

    int updateByExample(@Param("record") SysWarehousesTEntity record, @Param("example") SysWarehousesTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_WAREHOUSES_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") SysWarehousesTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_WAREHOUSES_V
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") SysWarehousesTExample example);
}