package com.wms.dao.auto;

import com.wms.dao.example.TaskDetailTExample;
import com.wms.entity.auto.TaskDetailTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ITaskDetailTDao {
    long countByExample(TaskDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") TaskDetailTExample example);

    int deleteByExample(TaskDetailTExample example);

    int insert(TaskDetailTEntity record);

    int insertSelective(TaskDetailTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TaskDetailTEntity selectOneByExample(TaskDetailTExample example);

    List<TaskDetailTEntity> selectByExample(TaskDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") TaskDetailTEntity record, @Param("example") TaskDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") TaskDetailTEntity record, @Param("example") TaskDetailTExample example);

    int updateByExampleSelective(@Param("record") TaskDetailTEntity record, @Param("example") TaskDetailTExample example);

    int updateByExample(@Param("record") TaskDetailTEntity record, @Param("example") TaskDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") TaskDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") TaskDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Long taskDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByPrimaryKey(@Param("version") Long version, @Param("key") Long taskDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASK_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TaskDetailTEntity selectByPrimaryKeyWithLogicalDelete(@Param("taskDetailId") Long taskDetailId, @Param("andLogicalDeleted") boolean andLogicalDeleted);
}