package com.wms.dao.auto;

import com.wms.dao.example.WaveBuildDetailTExample;
import com.wms.entity.auto.WaveBuildDetailTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IWaveBuildDetailTDao {
    long countByExample(WaveBuildDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WAVE_BUILD_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") WaveBuildDetailTExample example);

    int deleteByExample(WaveBuildDetailTExample example);

    int insert(WaveBuildDetailTEntity record);

    int insertSelective(WaveBuildDetailTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WAVE_BUILD_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WaveBuildDetailTEntity selectOneByExample(WaveBuildDetailTExample example);

    List<WaveBuildDetailTEntity> selectByExample(WaveBuildDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WAVE_BUILD_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") WaveBuildDetailTEntity record, @Param("example") WaveBuildDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WAVE_BUILD_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") WaveBuildDetailTEntity record, @Param("example") WaveBuildDetailTExample example);

    int updateByExampleSelective(@Param("record") WaveBuildDetailTEntity record, @Param("example") WaveBuildDetailTExample example);

    int updateByExample(@Param("record") WaveBuildDetailTEntity record, @Param("example") WaveBuildDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WAVE_BUILD_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") WaveBuildDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WAVE_BUILD_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") WaveBuildDetailTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WAVE_BUILD_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Long waveBuildDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WAVE_BUILD_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByPrimaryKey(@Param("version") Long version, @Param("key") Long waveBuildDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WAVE_BUILD_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WaveBuildDetailTEntity selectByPrimaryKeyWithLogicalDelete(@Param("waveBuildDetailId") Long waveBuildDetailId, @Param("andLogicalDeleted") boolean andLogicalDeleted);
}