package com.wms.dao.auto;

import com.wms.dao.example.ZoneTExample;
import com.wms.entity.auto.ZoneTEntity;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IZoneTDao {
    long countByExample(ZoneTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int deleteWithVersionByExample(@Param("version") Long version, @Param("example") ZoneTExample example);

    int deleteByExample(ZoneTExample example);

    int insert(ZoneTEntity record);

    int insertSelective(ZoneTEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ZoneTEntity selectOneByExample(ZoneTExample example);

    List<ZoneTEntity> selectByExample(ZoneTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExample(@Param("version") Long version, @Param("record") ZoneTEntity record, @Param("example") ZoneTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateWithVersionByExampleSelective(@Param("version") Long version, @Param("record") ZoneTEntity record, @Param("example") ZoneTExample example);

    int updateByExampleSelective(@Param("record") ZoneTEntity record, @Param("example") ZoneTExample example);

    int updateByExample(@Param("record") ZoneTEntity record, @Param("example") ZoneTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ZoneTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByExample(@Param("version") Long version, @Param("example") ZoneTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Long zoneId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteWithVersionByPrimaryKey(@Param("version") Long version, @Param("key") Long zoneId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZONE_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ZoneTEntity selectByPrimaryKeyWithLogicalDelete(@Param("zoneId") Long zoneId, @Param("andLogicalDeleted") boolean andLogicalDeleted);
}