server:
 port: 8180
 servlet:
  context-path: /WMS-JBT
  tomcat:
   # tomcat的URI编码
   uri-encoding: UTF-8
   # tomcat最大线程数，默认为200
   max-threads: 800
   # Tomcat启动初始化的线程数，默认值25
   min-spare-threads: 30
    
mybatis:
 mapper-locations: classpath:mapper/**/*.xml
 type-aliases-package: com.wms.entity

pagehelper:
 helperDialect: oracle
 reasonable: true
 supportMethodsArguments: true
 params: count=countByExample
 pagesize: 20
 pagelist: 20,50,100,500,1000
 
#logging:
# level:
#  com.wms.dao: debug
#  com.wms.aspect.RestAspect: debug
#  com.wms.services.core: debug
#  com.wms.services.allocate: debug
 
#uidGenerator:
# workerId: 1
# datacenterId: 1
 
 
# Spring配置
spring:
 # 模板引擎
 thymeleaf:
  mode: HTML
  encoding: utf-8
  # 禁用缓存
  cache: false
 # 文件上传
 servlet:
   multipart:
    max-file-size: 30MB
    max-request-size: 30MB
 #设置编码
 http: 
  encoding: 
   force: true
   charset: UTF-8
   enabled: true
# jackson:
#  time-zone: GMT+8
#  date-format: yyyy-MM-dd HH:mm:ss
 fastjson:
  date-format: yyyy-MM-dd HH:mm:ss
 jmx:
  enabled: false
   
# Shiro
shiro:
 ehcache: classpath:config/ehcache/ehcache-shiro.xml
 anon: /login,/mobile/login,/services/**,/static/**,/druid/**,/captcha/captchaImage**
 user:
  # 登录地址
  loginUrl: /web/login
 #登出地址
  logoutUrl: /web/logout
  # 权限认证失败地址
  unauthorizedUrl: /web/unauth
  # 首页地址
  indexUrl: /web/main
  # 验证码开关
  captchaEnabled: false
  # 验证码类型 math 数组计算 char 字符
  captchaType: math
 cookie:
  # 设置Cookie的域名 默认空，即当前访问的域名
  domain: 
  # 设置cookie的有效访问路径
  path: /
  # 设置HttpOnly属性
  httpOnly: true
  # 设置Cookie的过期时间，天为单位
  maxAge: 30
 session:
  # Session超时时间（默认30分钟）
  expireTime: 30
  # 同步session到数据库的周期（默认1分钟）
  dbSyncPeriod: 1
  # 相隔多久检查一次session的有效性，默认就是10分钟
  validationInterval: 10

# 防止XSS攻击
xss: 
 # 过滤开关
 enabled: true
 # 排除链接（多个用逗号分隔）
 excludes: /system/notice/*
 # 匹配链接
 urlPatterns: /system/*,/monitor/*,/tool/*
 
# 用户配置
user:
 password:
     # 密码错误{maxRetryCount}次锁定10分钟
  maxRetryCount: 5
  
wms:
 addressEnabled: false
 locale: en_US
 
#本地强制指定输出目录
#logging:
# path: D:\\logs
 