server:
 port: 8380
 servlet:
  context-path: /wms-report
  tomcat:
   # tomcat的URI编码
   uri-encoding: UTF-8
   # tomcat最大线程数，默认为200
   max-threads: 800
   # Tomcat启动初始化的线程数，默认值25
   min-spare-threads: 30

mybatis:
 mapper-locations: classpath:mapper/**/*.xml
 type-aliases-package: com.wms.entity


logging:
 level:
  com.wms.dao: debug
  com.wms.aspect.RestAspect: debug

birt:
 location:
  log: c:/birt
  chat:
   image: c:/birt-image/
 
 
# Spring配置
spring:
 # 文件上传
 servlet:
   multipart:
    max-file-size: 30MB
    max-request-size: 30MB
 #设置编码
 http: 
  encoding: 
   force: true
   charset: UTF-8
   enabled: true
# jackson:
#  time-zone: GMT+8
#  date-format: yyyy-MM-dd HH:mm:ss
 fastjson:
  date-format: yyyy-MM-dd HH:mm:ss
 jmx:
  enabled: false
  
wms:
 addressEnabled: false
 locale: zh_CN
  