package com.wms.entity.auto;

import com.wms.entity.BaseEntity;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

public class PackTEntity extends BaseEntity {
    private Long packId;

    private String packCode;

    private String packDescr;

    private String uom;

    private BigDecimal qty;

    private String uomInner;

    private BigDecimal qtyInner;

    private String uomCase;

    private BigDecimal qtyCase;

    private String active;

    private String remark;

    private Long companyId;

    private Long warehouseId;

    private String delFlag;

    private String createBy;

    private Date createTime;

    private String updateBy;

    private Date updateTime;

    private Long updateVersion;

    private String description;

    private BigDecimal volumeInner;

    private BigDecimal lengthInner;

    private BigDecimal widthInner;

    private BigDecimal heightInner;

    private BigDecimal weightGrossInner;

    private BigDecimal weightNetInner;

    private BigDecimal weightTareInner;

    private BigDecimal volumeCase;

    private BigDecimal lengthCase;

    private BigDecimal widthCase;

    private BigDecimal heightCase;

    private BigDecimal weightGrossCase;

    private BigDecimal weightNetCase;

    private BigDecimal weightTareCase;

    public Long getPackId() {
        return packId;
    }

    public void setPackId(Long packId) {
        this.packId = packId;
    }

    public String getPackCode() {
        return packCode;
    }

    public void setPackCode(String packCode) {
        this.packCode = packCode == null ? null : packCode.trim();
    }

    public String getPackDescr() {
        return packDescr;
    }

    public void setPackDescr(String packDescr) {
        this.packDescr = packDescr == null ? null : packDescr.trim();
    }

    public String getUom() {
        return uom;
    }

    public void setUom(String uom) {
        this.uom = uom == null ? null : uom.trim();
    }

    public BigDecimal getQty() {
        return qty;
    }

    public void setQty(BigDecimal qty) {
        this.qty = qty;
    }

    public String getUomInner() {
        return uomInner;
    }

    public void setUomInner(String uomInner) {
        this.uomInner = uomInner == null ? null : uomInner.trim();
    }

    public BigDecimal getQtyInner() {
        return qtyInner;
    }

    public void setQtyInner(BigDecimal qtyInner) {
        this.qtyInner = qtyInner;
    }

    public String getUomCase() {
        return uomCase;
    }

    public void setUomCase(String uomCase) {
        this.uomCase = uomCase == null ? null : uomCase.trim();
    }

    public BigDecimal getQtyCase() {
        return qtyCase;
    }

    public void setQtyCase(BigDecimal qtyCase) {
        this.qtyCase = qtyCase;
    }

    public String getActive() {
        return active;
    }

    public void setActive(String active) {
        this.active = active == null ? null : active.trim();
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    public Long getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public Long getWarehouseId() {
        return warehouseId;
    }

    public void setWarehouseId(Long warehouseId) {
        this.warehouseId = warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PACK_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setDelFlag(deleted ? DelFlag.IS_DELETED.value() : DelFlag.NOT_DELETED.value());
    }

    public String getDelFlag() {
        return delFlag;
    }

    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    public String getCreateBy() {
        return createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getUpdateBy() {
        return updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Long getUpdateVersion() {
        return updateVersion;
    }

    public void setUpdateVersion(Long updateVersion) {
        this.updateVersion = updateVersion;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    public BigDecimal getVolumeInner() {
        return volumeInner;
    }

    public void setVolumeInner(BigDecimal volumeInner) {
        this.volumeInner = volumeInner;
    }

    public BigDecimal getLengthInner() {
        return lengthInner;
    }

    public void setLengthInner(BigDecimal lengthInner) {
        this.lengthInner = lengthInner;
    }

    public BigDecimal getWidthInner() {
        return widthInner;
    }

    public void setWidthInner(BigDecimal widthInner) {
        this.widthInner = widthInner;
    }

    public BigDecimal getHeightInner() {
        return heightInner;
    }

    public void setHeightInner(BigDecimal heightInner) {
        this.heightInner = heightInner;
    }

    public BigDecimal getWeightGrossInner() {
        return weightGrossInner;
    }

    public void setWeightGrossInner(BigDecimal weightGrossInner) {
        this.weightGrossInner = weightGrossInner;
    }

    public BigDecimal getWeightNetInner() {
        return weightNetInner;
    }

    public void setWeightNetInner(BigDecimal weightNetInner) {
        this.weightNetInner = weightNetInner;
    }

    public BigDecimal getWeightTareInner() {
        return weightTareInner;
    }

    public void setWeightTareInner(BigDecimal weightTareInner) {
        this.weightTareInner = weightTareInner;
    }

    public BigDecimal getVolumeCase() {
        return volumeCase;
    }

    public void setVolumeCase(BigDecimal volumeCase) {
        this.volumeCase = volumeCase;
    }

    public BigDecimal getLengthCase() {
        return lengthCase;
    }

    public void setLengthCase(BigDecimal lengthCase) {
        this.lengthCase = lengthCase;
    }

    public BigDecimal getWidthCase() {
        return widthCase;
    }

    public void setWidthCase(BigDecimal widthCase) {
        this.widthCase = widthCase;
    }

    public BigDecimal getHeightCase() {
        return heightCase;
    }

    public void setHeightCase(BigDecimal heightCase) {
        this.heightCase = heightCase;
    }

    public BigDecimal getWeightGrossCase() {
        return weightGrossCase;
    }

    public void setWeightGrossCase(BigDecimal weightGrossCase) {
        this.weightGrossCase = weightGrossCase;
    }

    public BigDecimal getWeightNetCase() {
        return weightNetCase;
    }

    public void setWeightNetCase(BigDecimal weightNetCase) {
        this.weightNetCase = weightNetCase;
    }

    public BigDecimal getWeightTareCase() {
        return weightTareCase;
    }

    public void setWeightTareCase(BigDecimal weightTareCase) {
        this.weightTareCase = weightTareCase;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", packId=").append(packId);
        sb.append(", packCode=").append(packCode);
        sb.append(", packDescr=").append(packDescr);
        sb.append(", uom=").append(uom);
        sb.append(", qty=").append(qty);
        sb.append(", uomInner=").append(uomInner);
        sb.append(", qtyInner=").append(qtyInner);
        sb.append(", uomCase=").append(uomCase);
        sb.append(", qtyCase=").append(qtyCase);
        sb.append(", active=").append(active);
        sb.append(", remark=").append(remark);
        sb.append(", companyId=").append(companyId);
        sb.append(", warehouseId=").append(warehouseId);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateVersion=").append(updateVersion);
        sb.append(", description=").append(description);
        sb.append(", volumeInner=").append(volumeInner);
        sb.append(", lengthInner=").append(lengthInner);
        sb.append(", widthInner=").append(widthInner);
        sb.append(", heightInner=").append(heightInner);
        sb.append(", weightGrossInner=").append(weightGrossInner);
        sb.append(", weightNetInner=").append(weightNetInner);
        sb.append(", weightTareInner=").append(weightTareInner);
        sb.append(", volumeCase=").append(volumeCase);
        sb.append(", lengthCase=").append(lengthCase);
        sb.append(", widthCase=").append(widthCase);
        sb.append(", heightCase=").append(heightCase);
        sb.append(", weightGrossCase=").append(weightGrossCase);
        sb.append(", weightNetCase=").append(weightNetCase);
        sb.append(", weightTareCase=").append(weightTareCase);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PackTEntity other = (PackTEntity) that;
        return (this.getPackId() == null ? other.getPackId() == null : this.getPackId().equals(other.getPackId()))
            && (this.getPackCode() == null ? other.getPackCode() == null : this.getPackCode().equals(other.getPackCode()))
            && (this.getPackDescr() == null ? other.getPackDescr() == null : this.getPackDescr().equals(other.getPackDescr()))
            && (this.getUom() == null ? other.getUom() == null : this.getUom().equals(other.getUom()))
            && (this.getQty() == null ? other.getQty() == null : this.getQty().equals(other.getQty()))
            && (this.getUomInner() == null ? other.getUomInner() == null : this.getUomInner().equals(other.getUomInner()))
            && (this.getQtyInner() == null ? other.getQtyInner() == null : this.getQtyInner().equals(other.getQtyInner()))
            && (this.getUomCase() == null ? other.getUomCase() == null : this.getUomCase().equals(other.getUomCase()))
            && (this.getQtyCase() == null ? other.getQtyCase() == null : this.getQtyCase().equals(other.getQtyCase()))
            && (this.getActive() == null ? other.getActive() == null : this.getActive().equals(other.getActive()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getCompanyId() == null ? other.getCompanyId() == null : this.getCompanyId().equals(other.getCompanyId()))
            && (this.getWarehouseId() == null ? other.getWarehouseId() == null : this.getWarehouseId().equals(other.getWarehouseId()))
            && (this.getDelFlag() == null ? other.getDelFlag() == null : this.getDelFlag().equals(other.getDelFlag()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateVersion() == null ? other.getUpdateVersion() == null : this.getUpdateVersion().equals(other.getUpdateVersion()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getVolumeInner() == null ? other.getVolumeInner() == null : this.getVolumeInner().equals(other.getVolumeInner()))
            && (this.getLengthInner() == null ? other.getLengthInner() == null : this.getLengthInner().equals(other.getLengthInner()))
            && (this.getWidthInner() == null ? other.getWidthInner() == null : this.getWidthInner().equals(other.getWidthInner()))
            && (this.getHeightInner() == null ? other.getHeightInner() == null : this.getHeightInner().equals(other.getHeightInner()))
            && (this.getWeightGrossInner() == null ? other.getWeightGrossInner() == null : this.getWeightGrossInner().equals(other.getWeightGrossInner()))
            && (this.getWeightNetInner() == null ? other.getWeightNetInner() == null : this.getWeightNetInner().equals(other.getWeightNetInner()))
            && (this.getWeightTareInner() == null ? other.getWeightTareInner() == null : this.getWeightTareInner().equals(other.getWeightTareInner()))
            && (this.getVolumeCase() == null ? other.getVolumeCase() == null : this.getVolumeCase().equals(other.getVolumeCase()))
            && (this.getLengthCase() == null ? other.getLengthCase() == null : this.getLengthCase().equals(other.getLengthCase()))
            && (this.getWidthCase() == null ? other.getWidthCase() == null : this.getWidthCase().equals(other.getWidthCase()))
            && (this.getHeightCase() == null ? other.getHeightCase() == null : this.getHeightCase().equals(other.getHeightCase()))
            && (this.getWeightGrossCase() == null ? other.getWeightGrossCase() == null : this.getWeightGrossCase().equals(other.getWeightGrossCase()))
            && (this.getWeightNetCase() == null ? other.getWeightNetCase() == null : this.getWeightNetCase().equals(other.getWeightNetCase()))
            && (this.getWeightTareCase() == null ? other.getWeightTareCase() == null : this.getWeightTareCase().equals(other.getWeightTareCase()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPackId() == null) ? 0 : getPackId().hashCode());
        result = prime * result + ((getPackCode() == null) ? 0 : getPackCode().hashCode());
        result = prime * result + ((getPackDescr() == null) ? 0 : getPackDescr().hashCode());
        result = prime * result + ((getUom() == null) ? 0 : getUom().hashCode());
        result = prime * result + ((getQty() == null) ? 0 : getQty().hashCode());
        result = prime * result + ((getUomInner() == null) ? 0 : getUomInner().hashCode());
        result = prime * result + ((getQtyInner() == null) ? 0 : getQtyInner().hashCode());
        result = prime * result + ((getUomCase() == null) ? 0 : getUomCase().hashCode());
        result = prime * result + ((getQtyCase() == null) ? 0 : getQtyCase().hashCode());
        result = prime * result + ((getActive() == null) ? 0 : getActive().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getCompanyId() == null) ? 0 : getCompanyId().hashCode());
        result = prime * result + ((getWarehouseId() == null) ? 0 : getWarehouseId().hashCode());
        result = prime * result + ((getDelFlag() == null) ? 0 : getDelFlag().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateVersion() == null) ? 0 : getUpdateVersion().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getVolumeInner() == null) ? 0 : getVolumeInner().hashCode());
        result = prime * result + ((getLengthInner() == null) ? 0 : getLengthInner().hashCode());
        result = prime * result + ((getWidthInner() == null) ? 0 : getWidthInner().hashCode());
        result = prime * result + ((getHeightInner() == null) ? 0 : getHeightInner().hashCode());
        result = prime * result + ((getWeightGrossInner() == null) ? 0 : getWeightGrossInner().hashCode());
        result = prime * result + ((getWeightNetInner() == null) ? 0 : getWeightNetInner().hashCode());
        result = prime * result + ((getWeightTareInner() == null) ? 0 : getWeightTareInner().hashCode());
        result = prime * result + ((getVolumeCase() == null) ? 0 : getVolumeCase().hashCode());
        result = prime * result + ((getLengthCase() == null) ? 0 : getLengthCase().hashCode());
        result = prime * result + ((getWidthCase() == null) ? 0 : getWidthCase().hashCode());
        result = prime * result + ((getHeightCase() == null) ? 0 : getHeightCase().hashCode());
        result = prime * result + ((getWeightGrossCase() == null) ? 0 : getWeightGrossCase().hashCode());
        result = prime * result + ((getWeightNetCase() == null) ? 0 : getWeightNetCase().hashCode());
        result = prime * result + ((getWeightTareCase() == null) ? 0 : getWeightTareCase().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PACK_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static PackTEntity.Builder builder() {
        return new PackTEntity.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PACK_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table PACK_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private PackTEntity obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PACK_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new PackTEntity();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.PACK_ID
         *
         * @param packId the value for PACK_T.PACK_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder packId(Long packId) {
            obj.setPackId(packId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.PACK_CODE
         *
         * @param packCode the value for PACK_T.PACK_CODE
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder packCode(String packCode) {
            obj.setPackCode(packCode);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.PACK_DESCR
         *
         * @param packDescr the value for PACK_T.PACK_DESCR
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder packDescr(String packDescr) {
            obj.setPackDescr(packDescr);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.UOM
         *
         * @param uom the value for PACK_T.UOM
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder uom(String uom) {
            obj.setUom(uom);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.UOM_CASE
         *
         * @param uomCase the value for PACK_T.UOM_CASE
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder uomCase(String uomCase) {
            obj.setUomCase(uomCase);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.UOM_INNER
         *
         * @param uomInner the value for PACK_T.UOM_INNER
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder uomInner(String uomInner) {
            obj.setUomInner(uomInner);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.QTY
         *
         * @param qty the value for PACK_T.QTY
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder qty(BigDecimal qty) {
            obj.setQty(qty);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.QTY_CASE
         *
         * @param qtyCase the value for PACK_T.QTY_CASE
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder qtyCase(BigDecimal qtyCase) {
            obj.setQtyCase(qtyCase);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.QTY_INNER
         *
         * @param qtyInner the value for PACK_T.QTY_INNER
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder qtyInner(BigDecimal qtyInner) {
            obj.setQtyInner(qtyInner);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.ACTIVE
         *
         * @param active the value for PACK_T.ACTIVE
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder active(String active) {
            obj.setActive(active);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.REMARK
         *
         * @param remark the value for PACK_T.REMARK
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder remark(String remark) {
            obj.setRemark(remark);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.COMPANY_ID
         *
         * @param companyId the value for PACK_T.COMPANY_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder companyId(Long companyId) {
            obj.setCompanyId(companyId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.WAREHOUSE_ID
         *
         * @param warehouseId the value for PACK_T.WAREHOUSE_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder warehouseId(Long warehouseId) {
            obj.setWarehouseId(warehouseId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.DEL_FLAG
         *
         * @param delFlag the value for PACK_T.DEL_FLAG
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder delFlag(String delFlag) {
            obj.setDelFlag(delFlag);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.CREATE_BY
         *
         * @param createBy the value for PACK_T.CREATE_BY
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createBy(String createBy) {
            obj.setCreateBy(createBy);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.CREATE_TIME
         *
         * @param createTime the value for PACK_T.CREATE_TIME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createTime(Date createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.UPDATE_BY
         *
         * @param updateBy the value for PACK_T.UPDATE_BY
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateBy(String updateBy) {
            obj.setUpdateBy(updateBy);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.UPDATE_TIME
         *
         * @param updateTime the value for PACK_T.UPDATE_TIME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateTime(Date updateTime) {
            obj.setUpdateTime(updateTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.UPDATE_VERSION
         *
         * @param updateVersion the value for PACK_T.UPDATE_VERSION
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateVersion(Long updateVersion) {
            obj.setUpdateVersion(updateVersion);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.DESCRIPTION
         *
         * @param description the value for PACK_T.DESCRIPTION
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder description(String description) {
            obj.setDescription(description);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.VOLUME_INNER
         *
         * @param volumeInner the value for PACK_T.VOLUME_INNER
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder volumeInner(BigDecimal volumeInner) {
            obj.setVolumeInner(volumeInner);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.LENGTH_INNER
         *
         * @param lengthInner the value for PACK_T.LENGTH_INNER
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder lengthInner(BigDecimal lengthInner) {
            obj.setLengthInner(lengthInner);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.WIDTH_INNER
         *
         * @param widthInner the value for PACK_T.WIDTH_INNER
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder widthInner(BigDecimal widthInner) {
            obj.setWidthInner(widthInner);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.HEIGHT_INNER
         *
         * @param heightInner the value for PACK_T.HEIGHT_INNER
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder heightInner(BigDecimal heightInner) {
            obj.setHeightInner(heightInner);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.WEIGHT_GROSS_INNER
         *
         * @param weightGrossInner the value for PACK_T.WEIGHT_GROSS_INNER
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder weightGrossInner(BigDecimal weightGrossInner) {
            obj.setWeightGrossInner(weightGrossInner);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.WEIGHT_NET_INNER
         *
         * @param weightNetInner the value for PACK_T.WEIGHT_NET_INNER
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder weightNetInner(BigDecimal weightNetInner) {
            obj.setWeightNetInner(weightNetInner);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.WEIGHT_TARE_INNER
         *
         * @param weightTareInner the value for PACK_T.WEIGHT_TARE_INNER
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder weightTareInner(BigDecimal weightTareInner) {
            obj.setWeightTareInner(weightTareInner);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.VOLUME_CASE
         *
         * @param volumeCase the value for PACK_T.VOLUME_CASE
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder volumeCase(BigDecimal volumeCase) {
            obj.setVolumeCase(volumeCase);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.LENGTH_CASE
         *
         * @param lengthCase the value for PACK_T.LENGTH_CASE
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder lengthCase(BigDecimal lengthCase) {
            obj.setLengthCase(lengthCase);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.WIDTH_CASE
         *
         * @param widthCase the value for PACK_T.WIDTH_CASE
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder widthCase(BigDecimal widthCase) {
            obj.setWidthCase(widthCase);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.HEIGHT_CASE
         *
         * @param heightCase the value for PACK_T.HEIGHT_CASE
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder heightCase(BigDecimal heightCase) {
            obj.setHeightCase(heightCase);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.WEIGHT_GROSS_CASE
         *
         * @param weightGrossCase the value for PACK_T.WEIGHT_GROSS_CASE
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder weightGrossCase(BigDecimal weightGrossCase) {
            obj.setWeightGrossCase(weightGrossCase);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.WEIGHT_NET_CASE
         *
         * @param weightNetCase the value for PACK_T.WEIGHT_NET_CASE
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder weightNetCase(BigDecimal weightNetCase) {
            obj.setWeightNetCase(weightNetCase);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PACK_T.WEIGHT_TARE_CASE
         *
         * @param weightTareCase the value for PACK_T.WEIGHT_TARE_CASE
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder weightTareCase(BigDecimal weightTareCase) {
            obj.setWeightTareCase(weightTareCase);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PACK_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public PackTEntity build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table PACK_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum DelFlag {
        NOT_DELETED(new String("N"), "未删除"),
        IS_DELETED(new String("Y"), "已删除");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table PACK_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table PACK_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PACK_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        DelFlag(String value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PACK_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PACK_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PACK_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getName() {
            return this.name;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table PACK_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        packId("PACK_ID", "packId", "DECIMAL", false),
        packCode("PACK_CODE", "packCode", "VARCHAR", false),
        packDescr("PACK_DESCR", "packDescr", "VARCHAR", false),
        uom("UOM", "uom", "VARCHAR", false),
        qty("QTY", "qty", "DECIMAL", false),
        uomInner("UOM_INNER", "uomInner", "VARCHAR", false),
        qtyInner("QTY_INNER", "qtyInner", "DECIMAL", false),
        uomCase("UOM_CASE", "uomCase", "VARCHAR", false),
        qtyCase("QTY_CASE", "qtyCase", "DECIMAL", false),
        active("ACTIVE", "active", "CHAR", false),
        remark("REMARK", "remark", "VARCHAR", false),
        companyId("COMPANY_ID", "companyId", "DECIMAL", false),
        warehouseId("WAREHOUSE_ID", "warehouseId", "DECIMAL", false),
        delFlag("DEL_FLAG", "delFlag", "CHAR", false),
        createBy("CREATE_BY", "createBy", "VARCHAR", false),
        createTime("CREATE_TIME", "createTime", "TIMESTAMP", false),
        updateBy("UPDATE_BY", "updateBy", "VARCHAR", false),
        updateTime("UPDATE_TIME", "updateTime", "TIMESTAMP", false),
        updateVersion("UPDATE_VERSION", "updateVersion", "DECIMAL", false),
        description("DESCRIPTION", "description", "VARCHAR", false),
        volumeInner("VOLUME_INNER", "volumeInner", "DECIMAL", false),
        lengthInner("LENGTH_INNER", "lengthInner", "DECIMAL", false),
        widthInner("WIDTH_INNER", "widthInner", "DECIMAL", false),
        heightInner("HEIGHT_INNER", "heightInner", "DECIMAL", false),
        weightGrossInner("WEIGHT_GROSS_INNER", "weightGrossInner", "DECIMAL", false),
        weightNetInner("WEIGHT_NET_INNER", "weightNetInner", "DECIMAL", false),
        weightTareInner("WEIGHT_TARE_INNER", "weightTareInner", "DECIMAL", false),
        volumeCase("VOLUME_CASE", "volumeCase", "DECIMAL", false),
        lengthCase("LENGTH_CASE", "lengthCase", "DECIMAL", false),
        widthCase("WIDTH_CASE", "widthCase", "DECIMAL", false),
        heightCase("HEIGHT_CASE", "heightCase", "DECIMAL", false),
        weightGrossCase("WEIGHT_GROSS_CASE", "weightGrossCase", "DECIMAL", false),
        weightNetCase("WEIGHT_NET_CASE", "weightNetCase", "DECIMAL", false),
        weightTareCase("WEIGHT_TARE_CASE", "weightTareCase", "DECIMAL", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table PACK_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table PACK_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table PACK_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table PACK_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table PACK_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table PACK_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PACK_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PACK_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PACK_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PACK_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PACK_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PACK_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PACK_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PACK_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PACK_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PACK_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}