package com.wms.entity.auto;

import com.wms.entity.BaseEntity;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

public class PutawayStrategyDetailTEntity extends BaseEntity {
    private Long putawayStrategyDetailId;

    private Long putawayStrategyId;

    private Long lineNumber;

    private String type;

    private String fromLocationCode;

    private String fromZoneCode;

    private String toLocationCode;

    private String toZoneCode;

    private String sortRule;

    private String active;

    private String remark;

    private Long companyId;

    private Long warehouseId;

    private String delFlag;

    private String createBy;

    private Date createTime;

    private String updateBy;

    private Date updateTime;

    private Long updateVersion;

    private String description;

    public Long getPutawayStrategyDetailId() {
        return putawayStrategyDetailId;
    }

    public void setPutawayStrategyDetailId(Long putawayStrategyDetailId) {
        this.putawayStrategyDetailId = putawayStrategyDetailId;
    }

    public Long getPutawayStrategyId() {
        return putawayStrategyId;
    }

    public void setPutawayStrategyId(Long putawayStrategyId) {
        this.putawayStrategyId = putawayStrategyId;
    }

    public Long getLineNumber() {
        return lineNumber;
    }

    public void setLineNumber(Long lineNumber) {
        this.lineNumber = lineNumber;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    public String getFromLocationCode() {
        return fromLocationCode;
    }

    public void setFromLocationCode(String fromLocationCode) {
        this.fromLocationCode = fromLocationCode == null ? null : fromLocationCode.trim();
    }

    public String getFromZoneCode() {
        return fromZoneCode;
    }

    public void setFromZoneCode(String fromZoneCode) {
        this.fromZoneCode = fromZoneCode == null ? null : fromZoneCode.trim();
    }

    public String getToLocationCode() {
        return toLocationCode;
    }

    public void setToLocationCode(String toLocationCode) {
        this.toLocationCode = toLocationCode == null ? null : toLocationCode.trim();
    }

    public String getToZoneCode() {
        return toZoneCode;
    }

    public void setToZoneCode(String toZoneCode) {
        this.toZoneCode = toZoneCode == null ? null : toZoneCode.trim();
    }

    public String getSortRule() {
        return sortRule;
    }

    public void setSortRule(String sortRule) {
        this.sortRule = sortRule == null ? null : sortRule.trim();
    }

    public String getActive() {
        return active;
    }

    public void setActive(String active) {
        this.active = active == null ? null : active.trim();
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    public Long getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public Long getWarehouseId() {
        return warehouseId;
    }

    public void setWarehouseId(Long warehouseId) {
        this.warehouseId = warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUTAWAY_STRATEGY_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setDelFlag(deleted ? DelFlag.IS_DELETED.value() : DelFlag.NOT_DELETED.value());
    }

    public String getDelFlag() {
        return delFlag;
    }

    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    public String getCreateBy() {
        return createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getUpdateBy() {
        return updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Long getUpdateVersion() {
        return updateVersion;
    }

    public void setUpdateVersion(Long updateVersion) {
        this.updateVersion = updateVersion;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", putawayStrategyDetailId=").append(putawayStrategyDetailId);
        sb.append(", putawayStrategyId=").append(putawayStrategyId);
        sb.append(", lineNumber=").append(lineNumber);
        sb.append(", type=").append(type);
        sb.append(", fromLocationCode=").append(fromLocationCode);
        sb.append(", fromZoneCode=").append(fromZoneCode);
        sb.append(", toLocationCode=").append(toLocationCode);
        sb.append(", toZoneCode=").append(toZoneCode);
        sb.append(", sortRule=").append(sortRule);
        sb.append(", active=").append(active);
        sb.append(", remark=").append(remark);
        sb.append(", companyId=").append(companyId);
        sb.append(", warehouseId=").append(warehouseId);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", createBy=").append(createBy);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateVersion=").append(updateVersion);
        sb.append(", description=").append(description);
        sb.append("]");
        return sb.toString();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PutawayStrategyDetailTEntity other = (PutawayStrategyDetailTEntity) that;
        return (this.getPutawayStrategyDetailId() == null ? other.getPutawayStrategyDetailId() == null : this.getPutawayStrategyDetailId().equals(other.getPutawayStrategyDetailId()))
            && (this.getPutawayStrategyId() == null ? other.getPutawayStrategyId() == null : this.getPutawayStrategyId().equals(other.getPutawayStrategyId()))
            && (this.getLineNumber() == null ? other.getLineNumber() == null : this.getLineNumber().equals(other.getLineNumber()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getFromLocationCode() == null ? other.getFromLocationCode() == null : this.getFromLocationCode().equals(other.getFromLocationCode()))
            && (this.getFromZoneCode() == null ? other.getFromZoneCode() == null : this.getFromZoneCode().equals(other.getFromZoneCode()))
            && (this.getToLocationCode() == null ? other.getToLocationCode() == null : this.getToLocationCode().equals(other.getToLocationCode()))
            && (this.getToZoneCode() == null ? other.getToZoneCode() == null : this.getToZoneCode().equals(other.getToZoneCode()))
            && (this.getSortRule() == null ? other.getSortRule() == null : this.getSortRule().equals(other.getSortRule()))
            && (this.getActive() == null ? other.getActive() == null : this.getActive().equals(other.getActive()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getCompanyId() == null ? other.getCompanyId() == null : this.getCompanyId().equals(other.getCompanyId()))
            && (this.getWarehouseId() == null ? other.getWarehouseId() == null : this.getWarehouseId().equals(other.getWarehouseId()))
            && (this.getDelFlag() == null ? other.getDelFlag() == null : this.getDelFlag().equals(other.getDelFlag()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateVersion() == null ? other.getUpdateVersion() == null : this.getUpdateVersion().equals(other.getUpdateVersion()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPutawayStrategyDetailId() == null) ? 0 : getPutawayStrategyDetailId().hashCode());
        result = prime * result + ((getPutawayStrategyId() == null) ? 0 : getPutawayStrategyId().hashCode());
        result = prime * result + ((getLineNumber() == null) ? 0 : getLineNumber().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getFromLocationCode() == null) ? 0 : getFromLocationCode().hashCode());
        result = prime * result + ((getFromZoneCode() == null) ? 0 : getFromZoneCode().hashCode());
        result = prime * result + ((getToLocationCode() == null) ? 0 : getToLocationCode().hashCode());
        result = prime * result + ((getToZoneCode() == null) ? 0 : getToZoneCode().hashCode());
        result = prime * result + ((getSortRule() == null) ? 0 : getSortRule().hashCode());
        result = prime * result + ((getActive() == null) ? 0 : getActive().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getCompanyId() == null) ? 0 : getCompanyId().hashCode());
        result = prime * result + ((getWarehouseId() == null) ? 0 : getWarehouseId().hashCode());
        result = prime * result + ((getDelFlag() == null) ? 0 : getDelFlag().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateVersion() == null) ? 0 : getUpdateVersion().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUTAWAY_STRATEGY_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static PutawayStrategyDetailTEntity.Builder builder() {
        return new PutawayStrategyDetailTEntity.Builder();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PUTAWAY_STRATEGY_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table PUTAWAY_STRATEGY_DETAIL_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private PutawayStrategyDetailTEntity obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PUTAWAY_STRATEGY_DETAIL_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new PutawayStrategyDetailTEntity();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PUTAWAY_STRATEGY_DETAIL_T.PUTAWAY_STRATEGY_DETAIL_ID
         *
         * @param putawayStrategyDetailId the value for PUTAWAY_STRATEGY_DETAIL_T.PUTAWAY_STRATEGY_DETAIL_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder putawayStrategyDetailId(Long putawayStrategyDetailId) {
            obj.setPutawayStrategyDetailId(putawayStrategyDetailId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PUTAWAY_STRATEGY_DETAIL_T.PUTAWAY_STRATEGY_ID
         *
         * @param putawayStrategyId the value for PUTAWAY_STRATEGY_DETAIL_T.PUTAWAY_STRATEGY_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder putawayStrategyId(Long putawayStrategyId) {
            obj.setPutawayStrategyId(putawayStrategyId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PUTAWAY_STRATEGY_DETAIL_T.LINE_NUMBER
         *
         * @param lineNumber the value for PUTAWAY_STRATEGY_DETAIL_T.LINE_NUMBER
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder lineNumber(Long lineNumber) {
            obj.setLineNumber(lineNumber);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PUTAWAY_STRATEGY_DETAIL_T.TYPE
         *
         * @param type the value for PUTAWAY_STRATEGY_DETAIL_T.TYPE
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder type(String type) {
            obj.setType(type);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PUTAWAY_STRATEGY_DETAIL_T.FROM_LOCATION_CODE
         *
         * @param fromLocationCode the value for PUTAWAY_STRATEGY_DETAIL_T.FROM_LOCATION_CODE
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder fromLocationCode(String fromLocationCode) {
            obj.setFromLocationCode(fromLocationCode);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PUTAWAY_STRATEGY_DETAIL_T.FROM_ZONE_CODE
         *
         * @param fromZoneCode the value for PUTAWAY_STRATEGY_DETAIL_T.FROM_ZONE_CODE
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder fromZoneCode(String fromZoneCode) {
            obj.setFromZoneCode(fromZoneCode);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PUTAWAY_STRATEGY_DETAIL_T.TO_LOCATION_CODE
         *
         * @param toLocationCode the value for PUTAWAY_STRATEGY_DETAIL_T.TO_LOCATION_CODE
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder toLocationCode(String toLocationCode) {
            obj.setToLocationCode(toLocationCode);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PUTAWAY_STRATEGY_DETAIL_T.TO_ZONE_CODE
         *
         * @param toZoneCode the value for PUTAWAY_STRATEGY_DETAIL_T.TO_ZONE_CODE
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder toZoneCode(String toZoneCode) {
            obj.setToZoneCode(toZoneCode);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PUTAWAY_STRATEGY_DETAIL_T.SORT_RULE
         *
         * @param sortRule the value for PUTAWAY_STRATEGY_DETAIL_T.SORT_RULE
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder sortRule(String sortRule) {
            obj.setSortRule(sortRule);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PUTAWAY_STRATEGY_DETAIL_T.ACTIVE
         *
         * @param active the value for PUTAWAY_STRATEGY_DETAIL_T.ACTIVE
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder active(String active) {
            obj.setActive(active);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PUTAWAY_STRATEGY_DETAIL_T.REMARK
         *
         * @param remark the value for PUTAWAY_STRATEGY_DETAIL_T.REMARK
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder remark(String remark) {
            obj.setRemark(remark);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PUTAWAY_STRATEGY_DETAIL_T.COMPANY_ID
         *
         * @param companyId the value for PUTAWAY_STRATEGY_DETAIL_T.COMPANY_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder companyId(Long companyId) {
            obj.setCompanyId(companyId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PUTAWAY_STRATEGY_DETAIL_T.WAREHOUSE_ID
         *
         * @param warehouseId the value for PUTAWAY_STRATEGY_DETAIL_T.WAREHOUSE_ID
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder warehouseId(Long warehouseId) {
            obj.setWarehouseId(warehouseId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PUTAWAY_STRATEGY_DETAIL_T.DEL_FLAG
         *
         * @param delFlag the value for PUTAWAY_STRATEGY_DETAIL_T.DEL_FLAG
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder delFlag(String delFlag) {
            obj.setDelFlag(delFlag);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PUTAWAY_STRATEGY_DETAIL_T.CREATE_BY
         *
         * @param createBy the value for PUTAWAY_STRATEGY_DETAIL_T.CREATE_BY
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createBy(String createBy) {
            obj.setCreateBy(createBy);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PUTAWAY_STRATEGY_DETAIL_T.CREATE_TIME
         *
         * @param createTime the value for PUTAWAY_STRATEGY_DETAIL_T.CREATE_TIME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder createTime(Date createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PUTAWAY_STRATEGY_DETAIL_T.UPDATE_BY
         *
         * @param updateBy the value for PUTAWAY_STRATEGY_DETAIL_T.UPDATE_BY
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateBy(String updateBy) {
            obj.setUpdateBy(updateBy);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PUTAWAY_STRATEGY_DETAIL_T.UPDATE_TIME
         *
         * @param updateTime the value for PUTAWAY_STRATEGY_DETAIL_T.UPDATE_TIME
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateTime(Date updateTime) {
            obj.setUpdateTime(updateTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PUTAWAY_STRATEGY_DETAIL_T.UPDATE_VERSION
         *
         * @param updateVersion the value for PUTAWAY_STRATEGY_DETAIL_T.UPDATE_VERSION
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder updateVersion(Long updateVersion) {
            obj.setUpdateVersion(updateVersion);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column PUTAWAY_STRATEGY_DETAIL_T.DESCRIPTION
         *
         * @param description the value for PUTAWAY_STRATEGY_DETAIL_T.DESCRIPTION
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder description(String description) {
            obj.setDescription(description);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PUTAWAY_STRATEGY_DETAIL_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public PutawayStrategyDetailTEntity build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table PUTAWAY_STRATEGY_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum DelFlag {
        NOT_DELETED(new String("N"), "未删除"),
        IS_DELETED(new String("Y"), "已删除");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table PUTAWAY_STRATEGY_DETAIL_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table PUTAWAY_STRATEGY_DETAIL_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PUTAWAY_STRATEGY_DETAIL_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        DelFlag(String value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PUTAWAY_STRATEGY_DETAIL_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PUTAWAY_STRATEGY_DETAIL_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PUTAWAY_STRATEGY_DETAIL_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getName() {
            return this.name;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table PUTAWAY_STRATEGY_DETAIL_T
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        putawayStrategyDetailId("PUTAWAY_STRATEGY_DETAIL_ID", "putawayStrategyDetailId", "DECIMAL", false),
        putawayStrategyId("PUTAWAY_STRATEGY_ID", "putawayStrategyId", "DECIMAL", false),
        lineNumber("LINE_NUMBER", "lineNumber", "DECIMAL", false),
        type("TYPE", "type", "VARCHAR", true),
        fromLocationCode("FROM_LOCATION_CODE", "fromLocationCode", "VARCHAR", false),
        fromZoneCode("FROM_ZONE_CODE", "fromZoneCode", "VARCHAR", false),
        toLocationCode("TO_LOCATION_CODE", "toLocationCode", "VARCHAR", false),
        toZoneCode("TO_ZONE_CODE", "toZoneCode", "VARCHAR", false),
        sortRule("SORT_RULE", "sortRule", "VARCHAR", false),
        active("ACTIVE", "active", "CHAR", false),
        remark("REMARK", "remark", "VARCHAR", false),
        companyId("COMPANY_ID", "companyId", "DECIMAL", false),
        warehouseId("WAREHOUSE_ID", "warehouseId", "DECIMAL", false),
        delFlag("DEL_FLAG", "delFlag", "CHAR", false),
        createBy("CREATE_BY", "createBy", "VARCHAR", false),
        createTime("CREATE_TIME", "createTime", "TIMESTAMP", false),
        updateBy("UPDATE_BY", "updateBy", "VARCHAR", false),
        updateTime("UPDATE_TIME", "updateTime", "TIMESTAMP", false),
        updateVersion("UPDATE_VERSION", "updateVersion", "DECIMAL", false),
        description("DESCRIPTION", "description", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table PUTAWAY_STRATEGY_DETAIL_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table PUTAWAY_STRATEGY_DETAIL_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table PUTAWAY_STRATEGY_DETAIL_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table PUTAWAY_STRATEGY_DETAIL_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table PUTAWAY_STRATEGY_DETAIL_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table PUTAWAY_STRATEGY_DETAIL_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PUTAWAY_STRATEGY_DETAIL_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PUTAWAY_STRATEGY_DETAIL_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PUTAWAY_STRATEGY_DETAIL_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PUTAWAY_STRATEGY_DETAIL_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PUTAWAY_STRATEGY_DETAIL_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PUTAWAY_STRATEGY_DETAIL_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PUTAWAY_STRATEGY_DETAIL_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PUTAWAY_STRATEGY_DETAIL_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PUTAWAY_STRATEGY_DETAIL_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table PUTAWAY_STRATEGY_DETAIL_T
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}